// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://pk52eawoxzajjol3lhwcsghqmi.appsync-api.eu-west-2.amazonaws.com/graphql',
          region: 'eu-west-2',
          defaultAuthMode: 'userPool',
        }
    }
};

export default config;